root - ERROR - Exception occurred
Traceback (most recent call last):
  File "c:\python\BOOK\chapter 16 EXCEPTIONS\except6.py", line 8, in <module>
    result = 10 / 0
             ~~~^~~
ZeroDivisionError: division by zero
